inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/*
  TargetRubyVersion: 2.6
  NewCops: enable
Style/GlobalVars:
  Enabled: true
  AllowedVariables: [$redis]

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

require:
  - rubocop-performance
  - standard/cop/block_single_line_braces
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
