inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/*
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false  
Style/GlobalVars:
  Enabled: true
  AllowedVariables: [$redis]

RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

RSpec:
   Language:
     Expectations:
       - expect_passing_cfr_scenerio

plugins:
  - rubocop-performance
  - rubocop-rspec

require:
  - standard

inherit_gem:
  standard: config/base.yml
